### ISSUE TITLE
Structured annotations: check for text match

### ISSUE THREAD

**Issue by PabloMosUU** [vmenger/deduce#18]
The method deduce.annotate_text_structured returns structured annotations corresponding to the annotations embedded in the original text. It does so by reconstructing the original text from the annotated one, and keeping track of at which position the original text in the annotation would be placed. For example, in the text "I'm in love with Jane", annotated as "I'm in love with <PERSOON Jane>", the method finds the tag "<PERSOON Jane>", then computes the index of the opening angular bracket, and assumes that the word "Jane" in the original text occurs at the same location.

The trouble is that Deduce sometimes (accidentally) inserts or deletes a blank space, which messes with the indexing of the annotations in the original text. To mitigate this, we could access the original text to make sure that the annotation text matches what is present in the original text at that index.

**Comment by vmenger** [comment]
I think this was already fixed in 1.0.8, but definitely no longer relevant with 2.0.0, so closing it!

**Comment by PabloMosUU** [comment]
agreed
