### ISSUE TITLE
Long-term repository improvement plan

### ISSUE THREAD

**Issue by vmenger** [vmenger/deduce#22]
Recently, interest in DEDUCE is increasing: I get more messages/requests/questions, downloads are increasing, the repository has become somewhat alive. This must mean more people are using clinical text data, which is nice news. 

However, DEDUCE was created a long time ago with a specific problem in mind, by someone without much in depth python/dev experience (me). I now find the implementation of DEDUCE lacking in several aspects, and this in turn prevents making improvements to the algorithm itself. I intend to start fixing that, first improving just the implementation, and later potentially the algorithm too. Here I want to write out some of my ideas for improvements in the (near) future. 

Roughly I'm thinking of the following implementation changes (in this order), keeping the algorithm the same: 

- [x] Making everything pep8 compliant, maybe use black formatting, and write some basic contributing guidelines #23 
- [x] Refactor into a decent modular and object-oriented design (e.g. `Annotator`, `Pipeline`, `Tokenizer`, `Deduce` objects), with proper abstract base classes.
- [x] Split some of the rule-based deidentification logic into a separate meta-package, keeping the deduce-specific logic here. This should help greatly to provide building blocks for creating new/derived de-identification methods, for instance with more/other PHIs, without needing too much of a dev environment/background.
- [x] Adding proper unit testing, integration testing and coverage
- [x] Replacing the current in-text annotation logic with structured annotation logic. This one will be tricky to do without introducing changes to the algorithm, but we can go PHI by PHI. 
- [x] Replacing the current de-identification logic based on the structured annotations. This one should be more doable, but will still require some thought.
- [x] Find out where there are still idiosyncrasies (like nested tags, annotation order) and other obscurities preventing future changes, and mitigating them.
- [x] Check if any speed optimizations are possible (plus perhaps built-in multiprocessing)
- [x] Add documentation and guidelines for documentation
- [x] Separate configuration in a separate file/step (e.g. like [this](https://github.com/CogStack/MedCAT/blob/master/configs/base_train_selfsupervised.txt))
- [x] Add some good tutorials with examples, that should allow people to make their own rule-based de-identification models with the blocks coming from DEDUCE and/or the new meta-package. 
- [ ] If possible, have a proper test on an (open) annotated dataset to monitor performance
- [ ] Adding error handling and exceptions, including specification of what to do when an error occurs (raise warning / ignore / redact all text)
- [ ] Do a comparison with [nedap/deidentify](https://github.com/nedap/deidentify) on (1) a UMCU dataset and if possible (2) a 'neutral' dataset?

After that, we can start creating more building blocks (e.g. for new PHI categories we find interesting), and improving the building blocks we have, and by that make DEDUCE a more useful for cases outside Psychiatry. Ideally we would have a bit of an ecosystem developing around the rule-based deidentification problem, perhaps also outside medicine and in other languages. But, this is really still stuff for the future. 

This is all a bit stream of thought -- but please don't hesitate to add any comments or ideas! In a later stage I will try to structure and plan this a bit more in separate issues.

**Comment by vmenger** [comment]
@PabloMosUU I really value your work and input, so please feel free to add any comments you have

**Comment by PabloMosUU** [comment]
I mostly agree with everything you've written. I'm actually working on this at the moment as part of COVIDA. We can chat if you wish

**Comment by Torec** [comment]
Hey Vincent,

Nice to see that the repository is being updated again!

Just to let you know, at the AMC we have cloned and adjusted your software in the last few years to make it applicable for Dutch general practice (huisartsen) data. 
It is also open-sourced, as per the DEDUCE license: [https://bitbucket.org/aumc-kik/deduce-hag/](https://bitbucket.org/aumc-kik/deduce-hag/)

Sadly the changes were quite intrusive to the code, so it is unlikely that it can merge with your new code (or the other way around). However, maybe there are some parts you can re-use; e.g. there was some multiprocessing / speed optimizations done, and some tests or docker packaging.

> Split some of the rule-based deidentification logic into a separate meta-package, keeping the deduce-specific logic here. This should help greatly to provide building blocks for creating new/derived de-identification methods, for instance with more/other PHIs, without needing too much of a dev environment/background.

Indeed, this would have helped to have more cross-over code =)

Good luck & regards, 
Torec Luik

**Comment by vmenger** [comment]
Hi Torec, thanks for the message. I was made aware of the repo a while ago by one of your colleagues at AUMC, I appreciate that you made it open source. I looked through some of it, looks like you did a lot of useful changes for you data. 

Merging back will probably not be easy, however, in a later stage I would still like to discuss the possibility with you (or your group), especially now that AUMC is starting a bigger project around de-identification. But, I can totally see how merging is not a priority for you, especially since it's working fine at the moment, and the current DEDUCE repo does not allow it either. I'll probably try to get in touch with you in the future. 

Greetings!
Vincent

**Comment by PabloMosUU** [comment]
Hi Vincent,

I've just marked off almost all the empty boxes in the pull request for structured:
https://github.com/vmenger/deduce/pull/42
Attached is my report on comparing the current behaviour with the previous one. You can see that we are almost 100% in agreement, and the differences are minor, arising in edge cases, and not revealing sensitive information.

I also checked the time- and memory-efficiency. In terms of memory it looks very similar to before: about 0.3-0.4% of my computer's memory while running. Time has worsened by about 25%. I think, however, that the gains are greater than this loss, and that you will make it up once you start fixing bugs, removing unnecessary edge cases, etc.

If I were you, I'd merge it and give it a try. From my end, I think I will stop here. Please let me know if you have any questions.

Best,

Pablo

________________________________
