### ISSUE TITLE
annotate_names_context

### ISSUE THREAD

**Issue by PabloMosUU** [vmenger/deduce#6]
While working on the branch structured_annotations I came across the method deduce.annotate.annotate_names_context, but I can't find what it is used for. I've tried inputting texts in many formats, but I never found a case in which it did anything. Can you provide an example and/or tell me what the expected behaviour of this method is?

**Comment by vmenger** [comment]
I think the piece you are missing that text needs to go through annotate_names first:

``` 
t1 = annotate_names('V. Menger', patient_first_name='', patient_initial='', patient_surname='', patient_given_name='')
t2 = annotate_names_context(t1)

print(t1)
V. <ACHTERNAAMONBEKEND Menger>

print(t2)
<INITIAAL V. <ACHTERNAAMONBEKEND Menger>>

``` 

I totally agree that this could use improvement though.
