### ISSUE TITLE
Telephone number format not de-identified

### ISSUE THREAD

**Issue by sandertan** [vmenger/deduce#61]
The telephone number format `06 18 34 56 78` is currently not de-identified with DEDUCE. I suspect this format is not uncommon, so it might be worth adding functionality for it to DEDUCE.

```python
import deduce
text = u"De patient J. Jansen (e: j.jnsen@email.com, t: 06 18 34 56 78) is 64 jaar oud."
print(deduce.deidentify_annotations(deduce.annotate_text(text)))
```
> De \<PERSOON-1\> (e: \<URL-1\>, t: 06 18 34 56 78) is \<LEEFTIJD-1\> jaar oud.

Interestingly, the first 4 numbers can be recognized as date:
```python
import deduce
text = u"De patient J. Jansen (e: j.jnsen@email.com, t: 06 12 34 56 78) is 64 jaar oud."
print(deduce.deidentify_annotations(deduce.annotate_text(text)))
```
> De \<PERSOON-1\> (e: \<URL-1\>, t: \<DATUM-1\> 56 78) is \<LEEFTIJD-1\> jaar oud.

**Comment by vmenger** [comment]
Fixed in #89
