### ISSUE TITLE
Multiple consecutive spaces in patient identifers causes an IndexError

### ISSUE THREAD

**Issue by jacob-rousseau** [vmenger/deduce#73]
When there are multiple consecutive spaces present in the patient identifiers (e.g. patient_first_names, patient_last_names) then an
IndexError occurs duing the processing; see the stacktrace down below. The error occured with the input "Peter  Fiver" (with two spaces)  as patient first names

self = <deduce.pattern.name_patient.PersonInitialFromNamePattern object at 0x000001A6664C1AC0> 
token = Token(text='Peter', start_char=0, end_char=5) 
metadata = <docdeid.document.MetaData object at 0x000001A667603340> 
def match(self, token: dd.Token, metadata: dd.MetaData) -> Optional[tuple[dd.Token, dd.Token]]: 

for _, first_name in enumerate(metadata["patient"].first_names): 

> if str_match(token.text, first_name[0]): 
E IndexError: string index out of range 
..\venv\lib\site-packages\deduce\pattern\name_patient.py:47: IndexError

**Comment by vmenger** [comment]
If this still relevant, can you give a reproducible example? Thanks
