### ISSUE TITLE
Addition of annotations for long numbers conforming or not to a specific format

### ISSUE THREAD

**Issue by jacob-rousseau** [vmenger/deduce#74]
In medical texts tokens occur of long numbers such as the Dutch Social Number (Burger Service Number), BIG, AGB, bankaccounts. Some of these adhere to a specific format (e.g. IBAN) and/or to a specific mathematical algoritme (e.g. BSN and the 11-proof). 
To enhance the 'readablity' of anonymized texts number conforming to a format, could be annotated with a semantic meaningful annotation like [BSN] or [BANKACCOUTNUMBER]. On the other hand numbers not conforming to a format but could be annoated with a general annotation like [LONGNUMBER].

**Comment by vmenger** [comment]
Hi Jacob,

I added some new functionality (will release later this week) in #86 and #90:
* BSN nummers (that pass 11proef) are now annotated as BSN
* All numbers with at least 7 digits are now annotated as [ID]
* The patient identifier category has been removed

I did not find any examples of IBAN numbers, so I'll create a follow up feature request if someone wants to work on that. AGB and BIG numbers don't adhere to a specific format so they will remain tagged as [ID]. 

Let me know if you have any questions!
